### ISSUE TITLE
Symbols support

### ISSUE THREAD

**Issue by miguelsolorio** [maximedegreve/TinyFaces-Sketch-Plugin#3] opened 2017-02-01 04:21 UTC
Would be great if these could support symbols (like Craft), otherwise you're forced to not use symbols and that wouldn't be very fun.

**Comment by mikeprecious** [comment] 2017-02-01 17:15
+1 for Symbols support. Thanks for your work on this plugin!

**Comment by maximedegreve** [comment] 2017-02-04 06:07
Hi @miguelsolorio  & @mikeprecious 

Sounds good! Just a tiny question... How are your symbols structured? Should the plugin fill all shapes in the the symbol or just where already a image was added?

**Comment by maximedegreve** [comment] 2017-02-07 10:54
@miguelsolorio @mikeprecious Get the latest version! I've made a update which now supports groups and symbols... Let me know what you think...

**Comment by mikeprecious** [comment] 2017-02-08 00:00
Thanks! Grabbed the latest ver. Created a Circular Shape Layer and added a TinyFaces Fill. Then turned the Shape Layer into a Symbol. Then went back to the working Page in my Sketch doc with the Symbol instance in-hand and duplicated the Symbol 10 x 10 using InVision / Craft plugin. Craft duplicated the Symbol but the images did not vary - the same Fill image repeated. 

I have a bunch of images in a Dropbox folder. I performed the same procedure as above, and when using Craft, it grabbed a different image from the Dropbox folder for each new Symbol instance. 

I'm wondering what may be going on. I'm using the latest release of Sketch app.

**Comment by maximedegreve** [comment] 2017-02-08 10:42
@mikeprecious This is expected behaviour. You should make a symbol with a circle, with an image in there. And then place 10 times that symbol. Select all 10 symbols. Then use the TinyFaces plugin. It will ask you what shape in that symbol you want to fill with random data.

**Comment by maximedegreve** [comment] 2017-02-08 10:43
So duplicating a symbol will not automatically assign a new image to the contents. Being said that, I'm not ruling out a feature like this in the future.

**Comment by mikeprecious** [comment] 2017-02-09 11:41
@maximedegreve yes - that would be a fantastic option for the plugin. It falls inline well with rapid conceptualization processes, making it quicker and easier to manage variances in images without having to manually select and execute the Tiny Faces plugin every time a new instance of the symbol is created. 

Perhaps this idea would not replace the current, intended functionality - instead, be an "option" with the current functionality.

**Comment by maximedegreve** [comment] 2018-02-26 22:57
I'm closing this for now as the plugin supports symbols now.

**Closed by maximedegreve** 2018-02-26 22:57 UTC
