### ISSUE TITLE
No photos appear when using the plugin

### ISSUE THREAD

**Issue by diannealonsagay** [maximedegreve/TinyFaces-Sketch-Plugin#15] opened 2017-10-13 03:51 UTC
Sketch ver 47
TinyFaces ver 2.2

Problem: No photos appear when any options are used in the plugin

**Comment by gogolubev** [comment] 2017-10-13 13:15
Same problem. Same versions.

**Comment by mczachurski** [comment] 2017-10-15 15:10
I've the same issue.

**Comment by chadwhitaker** [comment] 2017-10-16 04:30
😞

**Comment by maximedegreve** [comment] 2017-10-16 08:10
Thank you for reporting this. I was able to reproduce this with the latest version of Sketch and will try to fix this ASAP.

**Comment by maximedegreve** [comment] 2017-10-16 08:19
The issue is no resolved in a new update of TinyFaces (2.3). 😃

**Comment by gogolubev** [comment] 2017-10-17 11:57
Thanks @maximedegreve

**Closed** 2017-10-17 13:42 UTC
