### ISSUE TITLE
Doesn't work with symbols

### ISSUE THREAD

**Issue by bstefan** [maximedegreve/TinyFaces-Sketch-Plugin#17] opened 2018-02-05 09:37 UTC
Doesn't work with symbols yet. The drop-down only contains the text layers.

https://www.dropbox.com/s/9g2cw11vr91i460/Screenshot%202018-02-05%2011.35.10.png?dl=0

Otherwise, great work. I really enjoy using this plugin!

**Comment by bradsiefert** [comment] 2018-02-21 23:02
I'm having the same issue.

**Comment by ninstorm** [comment] 2018-02-26 18:14
Even I am having the same issue. Please fix. Thanks

**Comment by maximedegreve** [comment] 2018-02-26 22:40
👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧

Hi @bstefan , @bradsiefert , @ninstorm 

Finally got some time to resolve this bug.
I've just pushed an update. Let me know if that works. 


👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧

**Comment by ninstorm** [comment] 2018-02-27 05:35
Thanks @maximedegreve. Symbols work again however, if a symbol has two layers, a text layer and rectangle, the plugin would ask for which layer to generate content for unlike earlier when it used to generate for both layers. Anyways, I am super happy that it works now.

**Comment by maximedegreve** [comment] 2018-02-27 08:42
@ninstorm Awwwwwwwesssssooome. That's intended behaviour as you wouldn't always want to replace every single shape in a symbol with random content. 👍

Closing this ❤️

**Closed by maximedegreve** 2018-02-27 08:42 UTC
