### ISSUE TITLE
Not working on El Capitan

### ISSUE THREAD

**Issue by Jojokats** [maximedegreve/TinyFaces-Sketch-Plugin#5] opened 2017-03-03 21:48 UTC
Hi, I am selecting a group of avatars to fill in with your plugin, but when selecting your option Fill with high quality or low quality, I don't get a dialogue box with options showing up and it only fills 1 avatar at a time not the group of avatars I have selected and there is no option for data. Something is wrong. Please advise. Thanks

**Comment by khalidadil** [comment] 2017-03-06 02:57
I'm seeing the same issue on Sketch version 42.

**Comment by maximedegreve** [comment] 2017-03-06 07:17
@Jojokats @khalidadil I can't reproduce this, do you have an example file I can try out?

**Comment by optimix-designer** [comment] 2017-03-23 17:10
Hi @maximedegreve,
Thanks for amazing plugin :)
Unfortunately, it seems that it doesn't work in Sketch 42 as other people mentioned. Please watch this short screencast:
[http://quick.as/laG1s0AAY](http://quick.as/laG1s0AAY).
I tried to re-install it several times, nothing helped :(
Can you please take a look? Thank you in advance!

**Comment by maximedegreve** [comment] 2017-03-25 09:10
Hi @optimix-designer thanks for that. This is really odd. I tried the exact same actions and this seems to work fine for me. Could you open the console app on your computer and try to use the plugin again. Then if something goes wrong this console app should give you more information why it's failing. Could you paste those errors here?

**Comment by optimix-designer** [comment] 2017-03-26 23:55
Hi @maximedegreve,
Thank you for quick response! I appreciate your support very much :)
I've made another test with recording both screen and console log. The screencast can be watched with the following link: [http://quick.as/P10XFJl7G](http://quick.as/P10XFJl7G)
Also there is a console log in the attachment.
[sketch-tinyfaces-console-log.txt](https://github.com/maximedegreve/TinyFaces-Sketch-Plugin/files/871167/sketch-tinyfaces-console-log.txt)
Thank you again!

**Comment by maximedegreve** [comment] 2017-03-27 08:18
@optimix-designer God this is bad :-( However now I know which method is causing the error. I have a slightly feeling one of the other plugins is hijacking that method. I will install a few of your plugins and see if I can reproduce it.

**Comment by optimix-designer** [comment] 2017-03-27 12:25
@maximedegreve Yes, I've got the same idea as soon as I couldn't make your plugin working after several re-installs. Previously I tried to disable most of newly installed plugins. But unfortunately, this trick didn't work :( 
Anyway, I keep believing that you will find a solution :)

**Comment by maximedegreve** [comment] 2017-03-30 13:41
@optimix-designer I just need to find a way to reproduce this. I might have to jump on a call with you or something. To figure out better what's going on...

**Comment by optimix-designer** [comment] 2017-04-02 14:44
@maximedegreve 
Ok, please let me know if you need my help :)
(though my English is far from perfect)

**Comment by devinhalladay** [comment] 2017-04-18 00:07
Hey @maximedegreve have you had any chance to look deeper into this? I'm happy to help debug if you need

**Comment by maximedegreve** [comment] 2017-04-18 09:42
@devinhalladay Would be great if we could jump on a Skype call or so? maxime.degreve

**Comment by ivanbabko** [comment] 2017-04-25 14:13
Hey guys, same issue here. Nothing happens when I try to use the plugin, just like on @optimix-designer's screencast. I'm using Sketch 43.2 (39069).

Attaching screenshot of my log. 
![screen shot 2017-04-25 at 16 10 41](https://cloud.githubusercontent.com/assets/196095/25389860/07d0c028-29d2-11e7-8e47-1654ea9b41e2.png)

**Comment by maximedegreve** [comment] 2017-05-07 16:47
@ivanbabko @devinhalladay @optimix-designer @Jojokats I've just made a new release. Can you check if this solves it?

**Comment by ivanbabko** [comment] 2017-05-07 18:20
@maximedegreve Just downloaded the plugin from your repo and installed it. Unfortunately I get the same error. I'll try to disable all other plugins and report back. Maybe there is a confilct? Here's my list of plugins:
![image](https://cloud.githubusercontent.com/assets/196095/25783814/a838ef4c-3362-11e7-8395-ede93f3cb3e6.png)

**Comment by ivanbabko** [comment] 2017-05-08 14:19
I disabled all plugins but TinyFaces, but it still didn't work for me :(

**Comment by maximedegreve** [comment] 2017-05-08 19:12
@ivanbabko Could you upload the sketch file + a video of what you do exactly? This might help a lot figuring out what is happening... I'm a bit clueless here....

**Comment by optimix-designer** [comment] 2017-05-08 22:34
@maximedegreve Uninstalled Tinyfaces plugin and installed v2.1 again (tried both manually and with Skecth Toolbox). Unfortunately, the problem is still here :(

**Comment by maximedegreve** [comment] 2017-05-09 10:42
@optimix-designer This is super weird....
What macOS version are you on?
This works fine for me:
https://www.dropbox.com/s/dcrnk11ab4yzuct/Weird.mov?dl=0

**Comment by ivanbabko** [comment] 2017-05-12 17:28
@optimix-designer OK, I think I know what was wrong. Your question about macOS version helped :) 
I was using El Capitan. After I've upgraded to Sierra the plugins works fine! THANK YOU!

**Comment by optimix-designer** [comment] 2017-05-18 11:30
@maximedegreve I currently use El Capitan (10.11.6). Unfortunately, I have to stick with current OS version and don't plan to upgrade to Sierra yet. Wish I would have the previous version of TinyFaces that was working well on El Capitan :)

**Comment by maximedegreve** [comment] 2017-05-29 06:38
@optimix-designer I will try to get my hand on a MacOS build of El Capitan and try to fix it. There might be work around for this!

**Comment by optimix-designer** [comment] 2017-06-10 19:23
@maximedegreve It sounds great! Thank you in advance! 😊

**Comment by maximedegreve** [comment] 2017-10-11 15:14
I'm closing this for now.

**Closed by maximedegreve** 2017-10-11 15:14 UTC

**Comment by optimix-designer** [comment] 2017-10-16 00:09
Hi @maximedegreve,
Any updates how to make the plugin working on El Capitan? Thank you!
